name: System
version: 2.0
author: ursinn
main: de.superlandnetwork.System.Main
depend: [API]
loadbefore: [API, BuildServer]
commands:
   cc:
   ChatClear:
   fly:
   night:
   nacht:
   day:
   tag:
   heal:
   feed:
   commandspy:
   forum:
   webseite:
   invsee:
   vanish:
   gm:
   gmc:
   gms:
   gma: